import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import KanbanProvider from "@/context";
import "./globals.css";

const jarkarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jarkarta.className} bg-tetiary-white-space antialiased`}
      >
        <KanbanProvider>{children}</KanbanProvider>
      </body>
    </html>
  );
}
